apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: xn2zzkzow-nodejs 
  janus-idp.io/tekton: xn2zzkzow-nodejs
  backstage.io/kubernetes-id: xn2zzkzow-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xn2zzkzow-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  